### ISSUE TITLE
Bot Status offline

### ISSUE THREAD

**Issue by Fresh-Kabbage** [shrubin/Genshin-Artifact-Rater#8]
Hi,

Our channel encountered an error on the bot.
Upon trying to -rate an artifact that has 2 substats to check if it will work
The Bot shown a timeout message
after 4 tries to check if it is Working
the Bot Shown that an unknown error has occured

The bot status are now offline (see image)
we tried kicking the bot but it was unkickable.
we also tried if the bot wont work on other channels. the bot still works on other channel

The artifact rater was a great help

So we are hoping for improvement. we also have ideas for the bot

![image](https://user-images.githubusercontent.com/75995064/102096351-8fc80e00-3e5f-11eb-9a71-e7278f88829b.png)

**Comment by shrubin** [comment]
Hi @Fresh-Kabbage, the bot has been down for a long time today due to Google's services going down. You may have seen some issues with Discord and other websites because of that.

For the timeout error, you should wait a few minutes before trying again, that happens when https://ocr.space servers go down.

If you're still having issues or want to share ideas, please join the artifact rater server at https://discord.gg/SyGmBxds3M
